class AppStrings {
  // keys: local code (en, ur, ar, es...), values: map of keys->string
  static const Map<String, Map<String, String>> localized = {
    'en': {
      'done': 'Done',
      'select_language': 'Select Language',
      'search_language': 'Search Language',
      'all_languages': 'All Languages',
      'next': 'Next',
      'lang_en': 'English',
      'lang_ar': 'Arabic',
      'lang_zh': 'Chinese',
      'lang_de': 'German',
      'lang_fr': 'French',
      'lang_id': 'Indonesian',
      'lang_ja': 'Japanese',
      'lang_pt': 'Portuguese',
      'lang_ru': 'Russian',
      'lang_tr': 'Turkish',
      'privacyPolicy': 'Privacy Policy',
      'rateUs': 'Rate Us',
      'shareApp': 'Share App',
      'settings': 'Settings',
      'languages': 'Languages',
      'home': 'Home',
      'editor': 'Editor',
      'addToHome': 'PDF added to Home',
      'pdfReader': 'PDF Reader',
      'searchFiles': 'Search recent files...',
      'allInOne': 'All in One\nPDF Reader',
      'readAndEdit': 'The easiest way \nto read and edit PDFs.',
      'recentFiles': 'Recent Files',
      'noRecentFiles': 'No recent files yet.',
      'print': 'Print',
      'rename': 'Rename',
      'share': 'Share',
      'delete': 'Delete',
      'renamePdf': 'Rename PDF',
      'newPdf': 'New name (without .pdf)',
      'cancel': 'Cancel',
      'renamedPdf': 'Renamed PDF',
      'editPdf': 'Edit PDF',
      'tapText': 'Tap on PDF to add text',
      'tapSignature': 'Tap on PDF to add signature',
      'tapComment': 'Tap on PDF to add a comment',
      'addText': 'Add text',
      'typeText': 'Type text Here',
      'add': 'Add',
      'addComment': 'Add Comment',
      'enterComment': 'Enter your comment...',
      'comment': 'Comment',
      'deleteComment': 'Delete Comment',
      'askPermissions': 'Please grant storage access in Settings',
      'permissionFallback': 'Storage permission denied. Saved in app folder.',
      'savedTo': 'Saved to',
      'searchDocument': 'Search in document...',
      'deleteQuestion': 'Do you want to remove this?',
      'deleteText': 'Delete Text',
      'text': 'Text',
      'signature': 'Signature',
      'color': 'Color',
      'background': 'Background',
      'size': 'Size',
      'bold': 'Bold',
      'italic': 'Italic',
      'opacity': 'Opacity',
      'uploadPdf': 'Upload Pdf',
      'uploadSignature': 'Upload Signature',
      'signInstructions':
          'Sign on white blank paper. After uploading you can drag signature on the PDF and Save.',
      'addComments': 'Add Hidden Comments',
      'commentInstructions':
          'Tap on the PDF to add a comment. A comment icon will appear. Tap the icon to view or edit your comment.',
      'readyComment': 'Ready to Add Comment',
      'skip': 'Skip',
      'continue': 'Continue',
      'Read Anytime, Anywhere': 'Read Anytime, Anywhere',
      'Access and read your favorite PDFs on the go with a smooth and intuitive experience.':
          'Access and read your favorite PDFs on the go with a smooth and intuitive experience.',
      'Edit PDFs Instantly': 'Edit PDFs Instantly',
      'Modify text, images, and pages in your PDF files with just a few taps — no extra tools needed.':
          'Modify text, images, and pages in your PDF files with just a few taps — no extra tools needed.',
      'Sign & Share Securely': 'Sign & Share Securely',
      'Add your digital signature and share documents safely with built-in privacy protection.':
          'Add your digital signature and share documents safely with built-in privacy protection.',
    },
    'ar': {
      'done': 'تم',
      'select_language': 'اختر اللغة',
      'search_language': 'ابحث عن لغة',
      'all_languages': 'جميع اللغات',
      'next': 'التالي',
      'lang_en': 'الإنجليزية',
      'lang_ar': 'العربية',
      'lang_zh': 'الصينية',
      'lang_de': 'الألمانية',
      'lang_fr': 'الفرنسية',
      'lang_id': 'الإندونيسية',
      'lang_ja': 'اليابانية',
      'lang_pt': 'البرتغالية',
      'lang_ru': 'الروسية',
      'lang_tr': 'التركية',
      'moreSettings': 'المزيد من الإعدادات',
      'privacyPolicy': 'سياسة الخصوصية',
      'rateUs': 'قيّمنا',
      'shareApp': 'مشاركة التطبيق',
      'settings': 'الإعدادات',
      'languages': 'اللغات',
      'home': 'الرئيسية',
      'editor': 'المحرر',
      'addToHome': 'تمت إضافة ملف PDF إلى الرئيسية',
      'pdfReader': 'قارئ PDF',
      'searchFiles': 'ابحث في الملفات الحديثة...',
      'allInOne': 'الكل في واحد\nقارئ PDF',
      'readAndEdit': 'أسهل طريقة\nلقراءة وتحرير ملفات PDF.',
      'recentFiles': 'الملفات الحديثة',
      'noRecentFiles': 'لا توجد ملفات حديثة بعد.',
      'print': 'طباعة',
      'rename': 'إعادة تسمية',
      'share': 'مشاركة',
      'delete': 'حذف',
      'renamePdf': 'إعادة تسمية PDF',
      'newPdf': 'اسم جديد (بدون .pdf)',
      'cancel': 'إلغاء',
      'renamedPdf': 'تمت إعادة تسمية ملف PDF',
      'editPdf': 'تحرير PDF',
      'tapText': 'انقر على PDF لإضافة نص',
      'tapSignature': 'انقر على PDF لإضافة توقيع',
      'tapComment': 'انقر على PDF لإضافة تعليق',
      'addText': 'إضافة نص',
      'typeText': 'اكتب النص هنا',
      'add': 'إضافة',
      'addComment': 'إضافة تعليق',
      'enterComment': 'أدخل تعليقك...',
      'comment': 'تعليق',
      'deleteComment': 'حذف التعليق',
      'askPermissions': 'يرجى منح إذن الوصول إلى التخزين من الإعدادات',
      'permissionFallback': 'تم رفض إذن التخزين. تم الحفظ في مجلد التطبيق.',
      'savedTo': 'تم الحفظ في',
      'searchDocument': 'ابحث في المستند...',
      'deleteQuestion': 'هل تريد إزالة هذا؟',
      'deleteText': 'حذف النص',
      'text': 'نص',
      'signature': 'توقيع',
      'color': 'اللون',
      'background': 'الخلفية',
      'size': 'الحجم',
      'bold': 'عريض',
      'italic': 'مائل',
      'opacity': 'الشفافية',
      'uploadPdf': 'رفع ملف PDF',
      'uploadSignature': 'رفع التوقيع',
      'signInstructions':
          'وقّع على ورقة بيضاء. بعد الرفع يمكنك سحب التوقيع على PDF ثم الحفظ.',
      'addComments': 'إضافة تعليقات مخفية',
      'commentInstructions':
          'انقر على PDF لإضافة تعليق. سيظهر رمز تعليق. انقر على الرمز لعرض أو تعديل تعليقك.',
      'readyComment': 'جاهز لإضافة تعليق',
      'skip': 'تخطي',
      'continue': 'متابعة',
      'Read Anytime, Anywhere': 'اقرأ في أي وقت وأي مكان',
      'Access and read your favorite PDFs on the go with a smooth and intuitive experience.':
          'يمكنك الوصول إلى ملفات PDF المفضلة وقراءتها أثناء التنقل بتجربة سلسة وبديهية.',
      'Edit PDFs Instantly': 'حرّر ملفات PDF فورًا',
      'Modify text, images, and pages in your PDF files with just a few taps — no extra tools needed.':
          'عدّل النصوص والصور والصفحات ببضع نقرات فقط — دون أدوات إضافية.',
      'Sign & Share Securely': 'وقّع وشارك بأمان',
      'Add your digital signature and share documents safely with built-in privacy protection.':
          'أضف توقيعك الرقمي وشارك المستندات بأمان مع حماية خصوصية مدمجة.',
    },
    'zh': {
      'done': '完成',
      'select_language': '选择语言',
      'search_language': '搜索语言',
      'all_languages': '所有语言',
      'next': '下一步',
      'lang_en': '英语',
      'lang_ar': '阿拉伯语',
      'lang_zh': '中文',
      'lang_de': '德语',
      'lang_fr': '法语',
      'lang_id': '印尼语',
      'lang_ja': '日语',
      'lang_pt': '葡萄牙语',
      'lang_ru': '俄语',
      'lang_tr': '土耳其语',
      'privacyPolicy': '隐私政策',
      'rateUs': '给我们评分',
      'shareApp': '分享应用',
      'settings': '设置',
      'languages': '语言',
      'home': '首页',
      'editor': '编辑器',
      'addToHome': 'PDF 已添加到首页',
      'pdfReader': 'PDF 阅读器',
      'searchFiles': '搜索最近的文件...',
      'allInOne': '一体化\nPDF 阅读器',
      'readAndEdit': '阅读和编辑 PDF 的最简单方式。',
      'recentFiles': '最近文件',
      'noRecentFiles': '尚无最近文件。',
      'print': '打印',
      'rename': '重命名',
      'share': '分享',
      'delete': '删除',
      'renamePdf': '重命名 PDF',
      'newPdf': '新名称（不含 .pdf）',
      'cancel': '取消',
      'renamedPdf': 'PDF 已重命名',
      'editPdf': '编辑 PDF',
      'tapText': '点击 PDF 添加文本',
      'tapSignature': '点击 PDF 添加签名',
      'tapComment': '点击 PDF 添加评论',
      'addText': '添加文本',
      'typeText': '在此输入文本',
      'add': '添加',
      'addComment': '添加评论',
      'enterComment': '输入你的评论...',
      'comment': '评论',
      'deleteComment': '删除评论',
      'askPermissions': '请在设置中授予存储访问权限',
      'permissionFallback': '存储权限被拒绝。已保存到应用文件夹。',
      'savedTo': '已保存到',
      'searchDocument': '在文档中搜索...',
      'deleteQuestion': '你想移除此项吗？',
      'deleteText': '删除文本',
      'text': '文本',
      'signature': '签名',
      'color': '颜色',
      'background': '背景',
      'size': '大小',
      'bold': '加粗',
      'italic': '斜体',
      'opacity': '不透明度',
      'uploadPdf': '上传 PDF',
      'uploadSignature': '上传签名',
      'signInstructions': '在白纸上签名。上传后可以将签名拖到 PDF 上并保存。',
      'addComments': '添加隐藏评论',
      'commentInstructions': '点击 PDF 添加评论。将出现评论图标。点击图标查看或编辑评论。',
      'readyComment': '准备添加评论',
      'skip': '跳过',
      'continue': '继续',
      'Read Anytime, Anywhere': '随时随地阅读',
      'Access and read your favorite PDFs on the go with a smooth and intuitive experience.':
          '随时随地访问并阅读你喜爱的 PDF，体验流畅直观。',
      'Edit PDFs Instantly': '即时编辑 PDF',
      'Modify text, images, and pages in your PDF files with just a few taps — no extra tools needed.':
          '只需轻点几下即可修改 PDF 中的文本、图像和页面，无需额外工具。',
      'Sign & Share Securely': '安全签署与分享',
      'Add your digital signature and share documents safely with built-in privacy protection.':
          '添加数字签名并安全分享文档，内置隐私保护。',
    },
    'de': {
      'done': 'Fertig',
      'select_language': 'Sprache auswählen',
      'search_language': 'Sprache suchen',
      'all_languages': 'Alle Sprachen',
      'next': 'Weiter',
      'lang_en': 'Englisch',
      'lang_ar': 'Arabisch',
      'lang_zh': 'Chinesisch',
      'lang_de': 'Deutsch',
      'lang_fr': 'Französisch',
      'lang_id': 'Indonesisch',
      'lang_ja': 'Japanisch',
      'lang_pt': 'Portugiesisch',
      'lang_ru': 'Russisch',
      'lang_tr': 'Türkisch',
      'privacyPolicy': 'Datenschutzrichtlinie',
      'rateUs': 'Bewerte uns',
      'shareApp': 'App teilen',
      'settings': 'Einstellungen',
      'languages': 'Sprachen',
      'home': 'Startseite',
      'editor': 'Editor',
      'addToHome': 'PDF zur Startseite hinzugefügt',
      'pdfReader': 'PDF-Reader',
      'searchFiles': 'Zuletzt verwendete Dateien durchsuchen...',
      'allInOne': 'All-in-One\nPDF-Reader',
      'readAndEdit': 'Die einfachste Art, PDFs zu lesen und zu bearbeiten.',
      'recentFiles': 'Zuletzt verwendet',
      'noRecentFiles': 'Noch keine zuletzt verwendeten Dateien.',
      'print': 'Drucken',
      'rename': 'Umbenennen',
      'share': 'Teilen',
      'delete': 'Löschen',
      'renamePdf': 'PDF umbenennen',
      'newPdf': 'Neuer Name (ohne .pdf)',
      'cancel': 'Abbrechen',
      'renamedPdf': 'PDF umbenannt',
      'editPdf': 'PDF bearbeiten',
      'tapText': 'Zum Hinzufügen von Text auf das PDF tippen',
      'tapSignature': 'Zum Hinzufügen einer Unterschrift tippen',
      'tapComment': 'Zum Hinzufügen eines Kommentars tippen',
      'addText': 'Text hinzufügen',
      'typeText': 'Text hier eingeben',
      'add': 'Hinzufügen',
      'addComment': 'Kommentar hinzufügen',
      'enterComment': 'Gib deinen Kommentar ein...',
      'comment': 'Kommentar',
      'deleteComment': 'Kommentar löschen',
      'askPermissions': 'Bitte erlaube Speicherzugriff in den Einstellungen',
      'permissionFallback':
          'Speicherzugriff verweigert. In App-Ordner gespeichert.',
      'savedTo': 'Gespeichert unter',
      'searchDocument': 'Im Dokument suchen...',
      'deleteQuestion': 'Möchtest du dies entfernen?',
      'deleteText': 'Text löschen',
      'text': 'Text',
      'signature': 'Unterschrift',
      'color': 'Farbe',
      'background': 'Hintergrund',
      'size': 'Größe',
      'bold': 'Fett',
      'italic': 'Kursiv',
      'opacity': 'Deckkraft',
      'uploadPdf': 'PDF hochladen',
      'uploadSignature': 'Unterschrift hochladen',
      'signInstructions':
          'Auf weißem Papier unterschreiben. Nach dem Hochladen kannst du die Unterschrift platzieren und speichern.',
      'addComments': 'Versteckte Kommentare hinzufügen',
      'commentInstructions':
          'Tippe auf das PDF, um einen Kommentar hinzuzufügen. Tippe auf das Symbol, um ihn anzusehen oder zu bearbeiten.',
      'readyComment': 'Bereit, einen Kommentar hinzuzufügen',
      'skip': 'Überspringen',
      'continue': 'Weiter',
      'Read Anytime, Anywhere': 'Überall und jederzeit lesen',
      'Access and read your favorite PDFs on the go with a smooth and intuitive experience.':
          'Greife unterwegs auf deine Lieblings‑PDFs zu und lies sie mit einer flüssigen, intuitiven Erfahrung.',
      'Edit PDFs Instantly': 'PDFs sofort bearbeiten',
      'Modify text, images, and pages in your PDF files with just a few taps — no extra tools needed.':
          'Bearbeite Text, Bilder und Seiten mit wenigen Tippbewegungen – ganz ohne Zusatztools.',
      'Sign & Share Securely': 'Sicher signieren & teilen',
      'Add your digital signature and share documents safely with built-in privacy protection.':
          'Füge deine digitale Unterschrift hinzu und teile Dokumente sicher – mit integriertem Datenschutz.',
    },
    'fr': {
      'done': 'Terminé',
      'select_language': 'Choisir la langue',
      'search_language': 'Rechercher une langue',
      'all_languages': 'Toutes les langues',
      'next': 'Suivant',
      'lang_en': 'Anglais',
      'lang_ar': 'Arabe',
      'lang_zh': 'Chinois',
      'lang_de': 'Allemand',
      'lang_fr': 'Français',
      'lang_id': 'Indonésien',
      'lang_ja': 'Japonais',
      'lang_pt': 'Portugais',
      'lang_ru': 'Russe',
      'lang_tr': 'Turc',
      'privacyPolicy': 'Politique de confidentialité',
      'rateUs': 'Nous évaluer',
      'shareApp': 'Partager l’application',
      'settings': 'Paramètres',
      'languages': 'Langues',
      'home': 'Accueil',
      'editor': 'Éditeur',
      'addToHome': 'PDF ajouté à l’accueil',
      'pdfReader': 'Lecteur PDF',
      'searchFiles': 'Rechercher des fichiers récents...',
      'allInOne': 'Lecteur PDF\nTout-en-un',
      'readAndEdit': 'La façon la plus simple de lire et modifier des PDF.',
      'recentFiles': 'Fichiers récents',
      'noRecentFiles': 'Aucun fichier récent pour le moment.',
      'print': 'Imprimer',
      'rename': 'Renommer',
      'share': 'Partager',
      'delete': 'Supprimer',
      'renamePdf': 'Renommer le PDF',
      'newPdf': 'Nouveau nom (sans .pdf)',
      'cancel': 'Annuler',
      'renamedPdf': 'PDF renommé',
      'editPdf': 'Modifier le PDF',
      'tapText': 'Touchez le PDF pour ajouter du texte',
      'tapSignature': 'Touchez le PDF pour ajouter une signature',
      'tapComment': 'Touchez le PDF pour ajouter un commentaire',
      'addText': 'Ajouter du texte',
      'typeText': 'Saisissez le texte ici',
      'add': 'Ajouter',
      'addComment': 'Ajouter un commentaire',
      'enterComment': 'Saisissez votre commentaire...',
      'comment': 'Commentaire',
      'deleteComment': 'Supprimer le commentaire',
      'askPermissions':
          'Veuillez accorder l’accès au stockage dans les réglages',
      'permissionFallback':
          'Accès au stockage refusé. Enregistré dans le dossier de l’app.',
      'savedTo': 'Enregistré dans',
      'searchDocument': 'Rechercher dans le document...',
      'deleteQuestion': 'Voulez-vous supprimer ceci ?',
      'deleteText': 'Supprimer le texte',
      'text': 'Texte',
      'signature': 'Signature',
      'color': 'Couleur',
      'background': 'Arrière-plan',
      'size': 'Taille',
      'bold': 'Gras',
      'italic': 'Italique',
      'opacity': 'Opacité',
      'uploadPdf': 'Téléverser un PDF',
      'uploadSignature': 'Téléverser une signature',
      'signInstructions':
          'Signez sur une feuille blanche. Après l’envoi, placez la signature sur le PDF et enregistrez.',
      'addComments': 'Ajouter des commentaires cachés',
      'commentInstructions':
          'Touchez le PDF pour ajouter un commentaire. Touchez l’icône pour voir ou modifier.',
      'readyComment': 'Prêt à ajouter un commentaire',
      'skip': 'Passer',
      'continue': 'Continuer',
      'Read Anytime, Anywhere': 'Lisez partout, à tout moment',
      'Access and read your favorite PDFs on the go with a smooth and intuitive experience.':
          'Accédez à vos PDF favoris et lisez‑les partout avec une expérience fluide et intuitive.',
      'Edit PDFs Instantly': 'Modifiez vos PDF instantanément',
      'Modify text, images, and pages in your PDF files with just a few taps — no extra tools needed.':
          'Modifiez textes, images et pages en quelques gestes — sans outil supplémentaire.',
      'Sign & Share Securely': 'Signez et partagez en toute sécurité',
      'Add your digital signature and share documents safely with built-in privacy protection.':
          'Ajoutez votre signature numérique et partagez vos documents en toute sécurité grâce à la protection de la confidentialité intégrée.',
    },
    'id': {
      'done':'Selesai' ,
      'select_language': 'Pilih Bahasa',
      'search_language': 'Cari Bahasa',
      'all_languages': 'Semua Bahasa',
      'next': 'Berikutnya',
      'lang_en': 'Bahasa Inggris',
      'lang_ar': 'Bahasa Arab',
      'lang_zh': 'Bahasa Tionghoa',
      'lang_de': 'Bahasa Jerman',
      'lang_fr': 'Bahasa Prancis',
      'lang_id': 'Bahasa Indonesia',
      'lang_ja': 'Bahasa Jepang',
      'lang_pt': 'Bahasa Portugis',
      'lang_ru': 'Bahasa Rusia',
      'lang_tr': 'Bahasa Turki',
      'privacyPolicy': 'Kebijakan Privasi',
      'rateUs': 'Beri Rating',
      'shareApp': 'Bagikan Aplikasi',
      'settings': 'Pengaturan',
      'languages': 'Bahasa',
      'home': 'Beranda',
      'editor': 'Editor',
      'addToHome': 'PDF ditambahkan ke Beranda',
      'pdfReader': 'Pembaca PDF',
      'searchFiles': 'Cari file terbaru...',
      'allInOne': 'Semua dalam Satu\nPembaca PDF',
      'readAndEdit': 'Cara termudah untuk membaca dan mengedit PDF.',
      'recentFiles': 'File Terbaru',
      'noRecentFiles': 'Belum ada file terbaru.',
      'print': 'Cetak',
      'rename': 'Ganti nama',
      'share': 'Bagikan',
      'delete': 'Hapus',
      'renamePdf': 'Ganti nama PDF',
      'newPdf': 'Nama baru (tanpa .pdf)',
      'cancel': 'Batal',
      'renamedPdf': 'PDF telah diganti nama',
      'editPdf': 'Edit PDF',
      'tapText': 'Ketuk PDF untuk menambahkan teks',
      'tapSignature': 'Ketuk untuk menambahkan tanda tangan',
      'tapComment': 'Ketuk untuk menambahkan komentar',
      'addText': 'Tambahkan teks',
      'typeText': 'Ketik teks di sini',
      'add': 'Tambahkan',
      'addComment': 'Tambahkan Komentar',
      'enterComment': 'Masukkan komentar Anda...',
      'comment': 'Komentar',
      'deleteComment': 'Hapus Komentar',
      'askPermissions': 'Mohon izinkan akses penyimpanan di Pengaturan',
      'permissionFallback':
          'Izin penyimpanan ditolak. Disimpan di folder aplikasi.',
      'savedTo': 'Disimpan ke',
      'searchDocument': 'Cari dalam dokumen...',
      'deleteQuestion': 'Apakah Anda ingin menghapus ini?',
      'deleteText': 'Hapus Teks',
      'text': 'Teks',
      'signature': 'Tanda tangan',
      'color': 'Warna',
      'background': 'Latar belakang',
      'size': 'Ukuran',
      'bold': 'Tebal',
      'italic': 'Miring',
      'opacity': 'Opasitas',
      'uploadPdf': 'Unggah PDF',
      'uploadSignature': 'Unggah Tanda Tangan',
      'signInstructions':
          'Tanda tangani di kertas putih. Setelah diunggah, seret tanda tangan ke PDF lalu simpan.',
      'addComments': 'Tambahkan Komentar Tersembunyi',
      'commentInstructions':
          'Ketuk PDF untuk menambahkan komentar. Ketuk ikon untuk melihat atau mengeditnya.',
      'readyComment': 'Siap Menambahkan Komentar',
      'skip': 'Lewati',
      'continue': 'Lanjut',
      'Read Anytime, Anywhere': 'Baca Kapan Saja, di Mana Saja',
      'Access and read your favorite PDFs on the go with a smooth and intuitive experience.':
          'Akses dan baca PDF favorit saat bepergian dengan pengalaman yang mulus dan intuitif.',
      'Edit PDFs Instantly': 'Edit PDF Seketika',
      'Modify text, images, and pages in your PDF files with just a few taps — no extra tools needed.':
          'Ubah teks, gambar, dan halaman hanya dengan beberapa ketukan — tanpa alat tambahan.',
      'Sign & Share Securely': 'Tanda Tangani & Bagikan dengan Aman',
      'Add your digital signature and share documents safely with built-in privacy protection.':
          'Tambahkan tanda tangan digital dan bagikan dokumen dengan aman berkat perlindungan privasi bawaan.',
    },
    'ja': {
      'done': '完了',
      'select_language': '言語を選択',
      'search_language': '言語を検索',
      'all_languages': 'すべての言語',
      'next': '次へ',
      'lang_en': '英語',
      'lang_ar': 'アラビア語',
      'lang_zh': '中国語',
      'lang_de': 'ドイツ語',
      'lang_fr': 'フランス語',
      'lang_id': 'インドネシア語',
      'lang_ja': '日本語',
      'lang_pt': 'ポルトガル語',
      'lang_ru': 'ロシア語',
      'lang_tr': 'トルコ語',
      'privacyPolicy': 'プライバシーポリシー',
      'rateUs': '評価する',
      'shareApp': 'アプリを共有',
      'settings': '設定',
      'languages': '言語',
      'home': 'ホーム',
      'editor': 'エディター',
      'addToHome': 'PDF をホームに追加しました',
      'pdfReader': 'PDF リーダー',
      'searchFiles': '最近のファイルを検索...',
      'allInOne': 'オールインワン\nPDF リーダー',
      'readAndEdit': 'PDF を読む・編集する最も簡単な方法。',
      'recentFiles': '最近のファイル',
      'noRecentFiles': '最近のファイルはありません。',
      'print': '印刷',
      'rename': '名前を変更',
      'share': '共有',
      'delete': '削除',
      'renamePdf': 'PDF の名前を変更',
      'newPdf': '新しい名前（.pdf を含まない）',
      'cancel': 'キャンセル',
      'renamedPdf': 'PDF を名前変更しました',
      'editPdf': 'PDF を編集',
      'tapText': 'PDF をタップしてテキストを追加',
      'tapSignature': 'PDF をタップして署名を追加',
      'tapComment': 'PDF をタップしてコメントを追加',
      'addText': 'テキストを追加',
      'typeText': 'ここにテキストを入力',
      'add': '追加',
      'addComment': 'コメントを追加',
      'enterComment': 'コメントを入力...',
      'comment': 'コメント',
      'deleteComment': 'コメントを削除',
      'askPermissions': '設定でストレージアクセスを許可してください',
      'permissionFallback': 'ストレージ権限が拒否されました。アプリのフォルダに保存しました。',
      'savedTo': '保存場所',
      'searchDocument': 'ドキュメント内を検索...',
      'deleteQuestion': 'これを削除しますか？',
      'deleteText': 'テキストを削除',
      'text': 'テキスト',
      'signature': '署名',
      'color': '色',
      'background': '背景',
      'size': 'サイズ',
      'bold': '太字',
      'italic': '斜体',
      'opacity': '不透明度',
      'uploadPdf': 'PDF をアップロード',
      'uploadSignature': '署名をアップロード',
      'signInstructions': '白い紙に署名してください。アップロード後、PDF 上に配置して保存できます。',
      'addComments': '非表示コメントを追加',
      'commentInstructions': 'PDF をタップしてコメントを追加。アイコンをタップして表示/編集します。',
      'readyComment': 'コメントの追加準備完了',
      'skip': 'スキップ',
      'continue': '続行',
      'Read Anytime, Anywhere': 'いつでもどこでも読む',
      'Access and read your favorite PDFs on the go with a smooth and intuitive experience.':
          'お気に入りのPDFにいつでもアクセスして、スムーズで直感的に閲覧できます。',
      'Edit PDFs Instantly': 'PDFをすぐ編集',
      'Modify text, images, and pages in your PDF files with just a few taps — no extra tools needed.':
          '数回のタップだけでテキスト・画像・ページを編集。追加ツールは不要です。',
      'Sign & Share Securely': '安全に署名して共有',
      'Add your digital signature and share documents safely with built-in privacy protection.':
          'デジタル署名を追加し、組み込みのプライバシー保護で安全に共有できます。',
    },
    'pt': {
      'done': 'Concluído',
      'select_language': 'Selecionar idioma',
      'search_language': 'Pesquisar idioma',
      'all_languages': 'Todos os idiomas',
      'next': 'Próximo',
      'lang_en': 'Inglês',
      'lang_ar': 'Árabe',
      'lang_zh': 'Chinês',
      'lang_de': 'Alemão',
      'lang_fr': 'Francês',
      'lang_id': 'Indonésio',
      'lang_ja': 'Japonês',
      'lang_pt': 'Português',
      'lang_ru': 'Russo',
      'lang_tr': 'Turco',
      'privacyPolicy': 'Política de Privacidade',
      'rateUs': 'Avalie-nos',
      'shareApp': 'Compartilhar App',
      'settings': 'Configurações',
      'languages': 'Idiomas',
      'home': 'Início',
      'editor': 'Editor',
      'addToHome': 'PDF adicionado à tela inicial',
      'pdfReader': 'Leitor de PDF',
      'searchFiles': 'Pesquisar arquivos recentes...',
      'allInOne': 'Leitor de PDF\nTudo em Um',
      'readAndEdit': 'A maneira mais fácil de ler e editar PDFs.',
      'recentFiles': 'Arquivos recentes',
      'noRecentFiles': 'Nenhum arquivo recente ainda.',
      'print': 'Imprimir',
      'rename': 'Renomear',
      'share': 'Compartilhar',
      'delete': 'Excluir',
      'renamePdf': 'Renomear PDF',
      'newPdf': 'Novo nome (sem .pdf)',
      'cancel': 'Cancelar',
      'renamedPdf': 'PDF renomeado',
      'editPdf': 'Editar PDF',
      'tapText': 'Toque no PDF para adicionar texto',
      'tapSignature': 'Toque no PDF para adicionar assinatura',
      'tapComment': 'Toque no PDF para adicionar um comentário',
      'addText': 'Adicionar texto',
      'typeText': 'Digite o texto aqui',
      'add': 'Adicionar',
      'addComment': 'Adicionar Comentário',
      'enterComment': 'Digite seu comentário...',
      'comment': 'Comentário',
      'deleteComment': 'Excluir Comentário',
      'askPermissions': 'Conceda acesso ao armazenamento nas Configurações',
      'permissionFallback': 'Permissão negada. Salvo na pasta do app.',
      'savedTo': 'Salvo em',
      'searchDocument': 'Pesquisar no documento...',
      'deleteQuestion': 'Deseja remover isto?',
      'deleteText': 'Excluir texto',
      'text': 'Texto',
      'signature': 'Assinatura',
      'color': 'Cor',
      'background': 'Fundo',
      'size': 'Tamanho',
      'bold': 'Negrito',
      'italic': 'Itálico',
      'opacity': 'Opacidade',
      'uploadPdf': 'Enviar PDF',
      'uploadSignature': 'Enviar Assinatura',
      'signInstructions':
          'Assine em papel branco. Após enviar, arraste a assinatura para o PDF e salve.',
      'addComments': 'Adicionar Comentários Ocultos',
      'commentInstructions':
          'Toque no PDF para adicionar um comentário. Toque no ícone para ver ou editar.',
      'readyComment': 'Pronto para adicionar comentário',
      'skip': 'Pular',
      'continue': 'Continuar',
      'Read Anytime, Anywhere': 'Leia a qualquer hora, em qualquer lugar',
      'Access and read your favorite PDFs on the go with a smooth and intuitive experience.':
          'Acesse e leia seus PDFs favoritos onde estiver, com uma experiência fluida e intuitiva.',
      'Edit PDFs Instantly': 'Edite PDFs instantaneamente',
      'Modify text, images, and pages in your PDF files with just a few taps — no extra tools needed.':
          'Modifique textos, imagens e páginas com poucos toques — sem ferramentas extras.',
      'Sign & Share Securely': 'Assine e compartilhe com segurança',
      'Add your digital signature and share documents safely with built-in privacy protection.':
          'Adicione sua assinatura digital e compartilhe com segurança, com proteção de privacidade integrada.',
    },
    'ru': {
      'done': 'Готово',
      'select_language': 'Выберите язык',
      'search_language': 'Поиск языка',
      'all_languages': 'Все языки',
      'next': 'Далее',
      'lang_en': 'Английский',
      'lang_ar': 'Арабский',
      'lang_zh': 'Китайский',
      'lang_de': 'Немецкий',
      'lang_fr': 'Французский',
      'lang_id': 'Индонезийский',
      'lang_ja': 'Японский',
      'lang_pt': 'Португальский',
      'lang_ru': 'Русский',
      'lang_tr': 'Турецкий',
      'privacyPolicy': 'Политика конфиденциальности',
      'rateUs': 'Оценить нас',
      'shareApp': 'Поделиться приложением',
      'settings': 'Настройки',
      'languages': 'Языки',
      'home': 'Главная',
      'editor': 'Редактор',
      'addToHome': 'PDF добавлен на главную',
      'pdfReader': 'PDF‑читалка',
      'searchFiles': 'Поиск недавних файлов...',
      'allInOne': 'Универсальный\nPDF‑читалка',
      'readAndEdit': 'Самый простой способ читать и редактировать PDF.',
      'recentFiles': 'Недавние файлы',
      'noRecentFiles': 'Недавних файлов пока нет.',
      'print': 'Печать',
      'rename': 'Переименовать',
      'share': 'Поделиться',
      'delete': 'Удалить',
      'renamePdf': 'Переименовать PDF',
      'newPdf': 'Новое имя (без .pdf)',
      'cancel': 'Отмена',
      'renamedPdf': 'PDF переименован',
      'editPdf': 'Редактировать PDF',
      'tapText': 'Нажмите на PDF, чтобы добавить текст',
      'tapSignature': 'Нажмите, чтобы добавить подпись',
      'tapComment': 'Нажмите, чтобы добавить комментарий',
      'addText': 'Добавить текст',
      'typeText': 'Введите текст здесь',
      'add': 'Добавить',
      'addComment': 'Добавить комментарий',
      'enterComment': 'Введите ваш комментарий...',
      'comment': 'Комментарий',
      'deleteComment': 'Удалить комментарий',
      'askPermissions': 'Предоставьте доступ к памяти в настройках',
      'permissionFallback':
          'Доступ к памяти отклонён. Сохранено в папку приложения.',
      'savedTo': 'Сохранено в',
      'searchDocument': 'Поиск по документу...',
      'deleteQuestion': 'Вы хотите удалить это?',
      'deleteText': 'Удалить текст',
      'text': 'Текст',
      'signature': 'Подпись',
      'color': 'Цвет',
      'background': 'Фон',
      'size': 'Размер',
      'bold': 'Жирный',
      'italic': 'Курсив',
      'opacity': 'Непрозрачность',
      'uploadPdf': 'Загрузить PDF',
      'uploadSignature': 'Загрузить подпись',
      'signInstructions':
          'Подпишите на белой бумаге. После загрузки разместите подпись на PDF и сохраните.',
      'addComments': 'Добавить скрытые комментарии',
      'commentInstructions':
          'Нажмите на PDF, чтобы добавить комментарий. Нажмите на значок для просмотра/редактирования.',
      'readyComment': 'Готово к добавлению комментария',
      'skip': 'Пропустить',
      'continue': 'Продолжить',
      'Read Anytime, Anywhere': 'Читайте в любое время и в любом месте',
      'Access and read your favorite PDFs on the go with a smooth and intuitive experience.':
          'Получайте доступ к любимым PDF и читайте их где угодно — быстро и удобно.',
      'Edit PDFs Instantly': 'Мгновенное редактирование PDF',
      'Modify text, images, and pages in your PDF files with just a few taps — no extra tools needed.':
          'Изменяйте текст, изображения и страницы в пару касаний — без лишних инструментов.',
      'Sign & Share Securely': 'Безопасная подпись и обмен',
      'Add your digital signature and share documents safely with built-in privacy protection.':
          'Добавляйте цифровую подпись и делитесь документами безопасно — с встроенной защитой конфиденциальности.',
    },
    'tr': {
      'done':'Tamamlandı' ,

      'select_language': 'Dili Seç',
      'search_language': 'Dil Ara',
      'all_languages': 'Tüm Diller',
      'next': 'İleri',
      'lang_en': 'İngilizce',
      'lang_ar': 'Arapça',
      'lang_zh': 'Çince',
      'lang_de': 'Almanca',
      'lang_fr': 'Fransızca',
      'lang_id': 'Endonezyaca',
      'lang_ja': 'Japonca',
      'lang_pt': 'Portekizce',
      'lang_ru': 'Rusça',
      'lang_tr': 'Türkçe',
      'privacyPolicy': 'Gizlilik Politikası',
      'rateUs': 'Bizi değerlendirin',
      'shareApp': 'Uygulamayı paylaş',
      'settings': 'Ayarlar',
      'languages': 'Diller',
      'home': 'Ana Sayfa',
      'editor': 'Düzenleyici',
      'addToHome': 'PDF Ana Sayfaya eklendi',
      'pdfReader': 'PDF Okuyucu',
      'searchFiles': 'Son dosyalarda ara...',
      'allInOne': 'Hepsi Bir Arada\nPDF Okuyucu',
      'readAndEdit': 'PDF okumak ve düzenlemek için en kolay yol.',
      'recentFiles': 'Son Dosyalar',
      'noRecentFiles': 'Henüz son dosya yok.',
      'print': 'Yazdır',
      'rename': 'Yeniden adlandır',
      'share': 'Paylaş',
      'delete': 'Sil',
      'renamePdf': 'PDF’yi Yeniden Adlandır',
      'newPdf': 'Yeni ad (.pdf olmadan)',
      'cancel': 'İptal',
      'renamedPdf': 'PDF yeniden adlandırıldı',
      'editPdf': 'PDF’yi Düzenle',
      'tapText': 'Metin eklemek için PDF’ye dokunun',
      'tapSignature': 'İmza eklemek için dokunun',
      'tapComment': 'Yorum eklemek için dokunun',
      'addText': 'Metin ekle',
      'typeText': 'Metni buraya yazın',
      'add': 'Ekle',
      'addComment': 'Yorum Ekle',
      'enterComment': 'Yorumunuzu yazın...',
      'comment': 'Yorum',
      'deleteComment': 'Yorumu Sil',
      'askPermissions': 'Lütfen Ayarlar’dan depolama erişimi verin',
      'permissionFallback':
          'Depolama izni reddedildi. Uygulama klasörüne kaydedildi.',
      'savedTo': 'Kaydedildi',
      'searchDocument': 'Belgede ara...',
      'deleteQuestion': 'Bunu kaldırmak istiyor musunuz?',
      'deleteText': 'Metni Sil',
      'text': 'Metin',
      'signature': 'İmza',
      'color': 'Renk',
      'background': 'Arka plan',
      'size': 'Boyut',
      'bold': 'Kalın',
      'italic': 'İtalik',
      'opacity': 'Opaklık',
      'uploadPdf': 'PDF Yükle',
      'uploadSignature': 'İmza Yükle',
      'signInstructions':
          'Beyaz kâğıda imzalayın. Yükledikten sonra PDF üzerine sürükleyip kaydedin.',
      'addComments': 'Gizli Yorumlar Ekle',
      'commentInstructions':
          'Yorum eklemek için PDF’ye dokunun. Görmek/düzenlemek için simgeye dokunun.',
      'readyComment': 'Yorum eklemeye hazır',
      'skip': 'Atla',
      'continue': 'Devam et',
      'Read Anytime, Anywhere': 'İstediğin zaman, istediğin yerde oku',
      'Access and read your favorite PDFs on the go with a smooth and intuitive experience.':
          'Favori PDF’lerine her yerde eriş ve akıcı, sezgisel bir deneyimle oku.',
      'Edit PDFs Instantly': 'PDF’leri anında düzenle',
      'Modify text, images, and pages in your PDF files with just a few taps — no extra tools needed.':
          'Metinleri, görselleri ve sayfaları birkaç dokunuşla düzenle — ek araca gerek yok.',
      'Sign & Share Securely': 'Güvenle imzala ve paylaş',
      'Add your digital signature and share documents safely with built-in privacy protection.':
          'Dijital imzanı ekle ve yerleşik gizlilik korumasıyla belgeleri güvenle paylaş.',
    },
  };
}
