class AppStrings {
  // keys: local code (en, ur, ar, es...), values: map of keys->string
  static const Map<String, Map<String, String>> localized = {
    'en': {
      'select_language': 'Select Language',
      'search_language': 'Search Language',
      'all_languages': 'All Languages',
      'next': 'Next',
      'lang_en': 'English',
      'lang_ar': 'Arabic',
      'lang_zh': 'Chinese',
      'lang_de': 'German',
      'lang_fr': 'French',
      'lang_id': 'Indonesian',
      'lang_ja': 'Japanese',
      'lang_pt': 'Portuguese',
      'lang_ru': 'Russian',
      'lang_tr': 'Turkish',
    },
    'ar': {
      'select_language': 'اختر اللغة',
      'search_language': 'ابحث عن لغة',
      'all_languages': 'جميع اللغات',
      'next': 'التالي',
      'lang_en': 'الإنجليزية',
      'lang_ar': 'العربية',
      'lang_zh': 'الصينية',
      'lang_de': 'الألمانية',
      'lang_fr': 'الفرنسية',
      'lang_id': 'الإندونيسية',
      'lang_ja': 'اليابانية',
      'lang_pt': 'البرتغالية',
      'lang_ru': 'الروسية',
      'lang_tr': 'التركية',
      'moreSettings': 'المزيد من الإعدادات',
    },
    'zh': {
      'select_language': '选择语言',
      'search_language': '搜索语言',
      'all_languages': '所有语言',
      'next': '下一步',
      'lang_en': '英语',
      'lang_ar': '阿拉伯语',
      'lang_zh': '中文',
      'lang_de': '德语',
      'lang_fr': '法语',
      'lang_id': '印尼语',
      'lang_ja': '日语',
      'lang_pt': '葡萄牙语',
      'lang_ru': '俄语',
      'lang_tr': '土耳其语',

    },
    'de': {

      'select_language': 'Sprache auswählen',
      'search_language': 'Sprache suchen',
      'all_languages': 'Alle Sprachen',
      'next': 'Weiter',
      'lang_en': 'Englisch',
      'lang_ar': 'Arabisch',
      'lang_zh': 'Chinesisch',
      'lang_de': 'Deutsch',
      'lang_fr': 'Französisch',
      'lang_id': 'Indonesisch',
      'lang_ja': 'Japanisch',
      'lang_pt': 'Portugiesisch',
      'lang_ru': 'Russisch',
      'lang_tr': 'Türkisch',
    },
    'fr': {
      'select_language': 'Choisir la langue',
      'search_language': 'Rechercher une langue',
      'all_languages': 'Toutes les langues',
      'next': 'Suivant',
      'lang_en': 'Anglais',
      'lang_ar': 'Arabe',
      'lang_zh': 'Chinois',
      'lang_de': 'Allemand',
      'lang_fr': 'Français',
      'lang_id': 'Indonésien',
      'lang_ja': 'Japonais',
      'lang_pt': 'Portugais',
      'lang_ru': 'Russe',
      'lang_tr': 'Turc',

    },
    'id': {

      'select_language': 'Pilih Bahasa',
      'search_language': 'Cari Bahasa',
      'all_languages': 'Semua Bahasa',
      'next': 'Berikutnya',
      'lang_en': 'Bahasa Inggris',
      'lang_ar': 'Bahasa Arab',
      'lang_zh': 'Bahasa Tionghoa',
      'lang_de': 'Bahasa Jerman',
      'lang_fr': 'Bahasa Prancis',
      'lang_id': 'Bahasa Indonesia',
      'lang_ja': 'Bahasa Jepang',
      'lang_pt': 'Bahasa Portugis',
      'lang_ru': 'Bahasa Rusia',
      'lang_tr': 'Bahasa Turki',
    },
    'ja': {
      'select_language': '言語を選択',
      'search_language': '言語を検索',
      'all_languages': 'すべての言語',
      'next': '次へ',
      'lang_en': '英語',
      'lang_ar': 'アラビア語',
      'lang_zh': '中国語',
      'lang_de': 'ドイツ語',
      'lang_fr': 'フランス語',
      'lang_id': 'インドネシア語',
      'lang_ja': '日本語',
      'lang_pt': 'ポルトガル語',
      'lang_ru': 'ロシア語',
      'lang_tr': 'トルコ語',

    },
    'pt': {
      'select_language': 'Selecionar idioma',
      'search_language': 'Pesquisar idioma',
      'all_languages': 'Todos os idiomas',
      'next': 'Próximo',
      'lang_en': 'Inglês',
      'lang_ar': 'Árabe',
      'lang_zh': 'Chinês',
      'lang_de': 'Alemão',
      'lang_fr': 'Francês',
      'lang_id': 'Indonésio',
      'lang_ja': 'Japonês',
      'lang_pt': 'Português',
      'lang_ru': 'Russo',
      'lang_tr': 'Turco',

    },
    'ru': {
      'select_language': 'Выберите язык',
      'search_language': 'Поиск языка',
      'all_languages': 'Все языки',
      'next': 'Далее',
      'lang_en': 'Английский',
      'lang_ar': 'Арабский',
      'lang_zh': 'Китайский',
      'lang_de': 'Немецкий',
      'lang_fr': 'Французский',
      'lang_id': 'Индонезийский',
      'lang_ja': 'Японский',
      'lang_pt': 'Португальский',
      'lang_ru': 'Русский',
      'lang_tr': 'Турецкий',
    },
    'tr': {
      'select_language': 'Dili Seç',
      'search_language': 'Dil Ara',
      'all_languages': 'Tüm Diller',
      'next': 'İleri',
      'lang_en': 'İngilizce',
      'lang_ar': 'Arapça',
      'lang_zh': 'Çince',
      'lang_de': 'Almanca',
      'lang_fr': 'Fransızca',
      'lang_id': 'Endonezyaca',
      'lang_ja': 'Japonca',
      'lang_pt': 'Portekizce',
      'lang_ru': 'Rusça',
      'lang_tr': 'Türkçe',
    },
  };
}
